name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Deploy User Metrics Service
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GH }}
      
      - name: Build with gradle
        env:
          GITHUB_ORG_REPO: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          ./gradlew bootBuildImage \
            && docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest \
            && docker push ghcr.io/${{ github.repository }}:latest